# Generated by Django 3.0.8 on 2020-09-08 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200908_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
