# Generated by Django 3.0.8 on 2020-09-09 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Internship_companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='', upload_to='dashboard/internship_img')),
                ('Company_name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('Job_role', models.CharField(max_length=30)),
                ('Job_role_description', models.CharField(max_length=30)),
                ('Contract_based', models.BooleanField(null=True)),
                ('Salary_offered', models.IntegerField(null=True)),
                ('Salary_in', models.CharField(default='LPA', max_length=10, null=True)),
                ('available_till', models.DateField(default=datetime.date.today, null=True)),
                ('Role_no_available', models.IntegerField(default=0, null=True)),
                ('cgpa_required', models.FloatField(default=3.5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='placement_companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='', upload_to='dashboard/placement_img')),
                ('Company_name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('Job_role', models.CharField(max_length=30)),
                ('Job_role_description', models.CharField(max_length=30)),
                ('Contract_based', models.BooleanField(null=True)),
                ('Salary_offered', models.IntegerField(null=True)),
                ('Salary_in', models.CharField(default='LPA', max_length=10, null=True)),
                ('cgpa_required', models.FloatField(default=3.5, null=True)),
                ('Role_no_available', models.IntegerField(null=True)),
                ('available_till', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='expert_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exper_field', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
